import type { Market, Stock } from "@/lib/types";

export const KOREAN_STOCKS: Stock[] = [
  { stockCode: "005930", stockName: "삼성전자", market: "KOSPI" },
  { stockCode: "000660", stockName: "SK하이닉스", market: "KOSPI" },
  { stockCode: "373220", stockName: "LG에너지솔루션", market: "KOSPI" },
  { stockCode: "207940", stockName: "삼성바이오로직스", market: "KOSPI" },
  { stockCode: "005380", stockName: "현대차", market: "KOSPI" },
  { stockCode: "005490", stockName: "POSCO홀딩스", market: "KOSPI" },
  { stockCode: "035420", stockName: "NAVER", market: "KOSPI" },
  { stockCode: "051910", stockName: "LG화학", market: "KOSPI" },
  { stockCode: "006400", stockName: "삼성SDI", market: "KOSPI" },
  { stockCode: "035720", stockName: "카카오", market: "KOSPI" },
  { stockCode: "000270", stockName: "기아", market: "KOSPI" },
  { stockCode: "068270", stockName: "셀트리온", market: "KOSPI" },
  { stockCode: "105560", stockName: "KB금융", market: "KOSPI" },
  { stockCode: "055550", stockName: "신한지주", market: "KOSPI" },
  { stockCode: "012330", stockName: "현대모비스", market: "KOSPI" },
  { stockCode: "028260", stockName: "삼성물산", market: "KOSPI" },
  { stockCode: "066570", stockName: "LG전자", market: "KOSPI" },
  { stockCode: "096770", stockName: "SK이노베이션", market: "KOSPI" },
  { stockCode: "034020", stockName: "두산에너빌리티", market: "KOSPI" },
  { stockCode: "003550", stockName: "LG", market: "KOSPI" },
  { stockCode: "015760", stockName: "한국전력", market: "KOSPI" },
  { stockCode: "017670", stockName: "SK텔레콤", market: "KOSPI" },
  { stockCode: "032830", stockName: "삼성생명", market: "KOSPI" },
  { stockCode: "010130", stockName: "고려아연", market: "KOSPI" },
  { stockCode: "086790", stockName: "하나금융지주", market: "KOSPI" },
  { stockCode: "316140", stockName: "우리금융지주", market: "KOSPI" },
  { stockCode: "009150", stockName: "삼성전기", market: "KOSPI" },
  { stockCode: "033780", stockName: "KT&G", market: "KOSPI" },
  { stockCode: "011200", stockName: "HMM", market: "KOSPI" },
  { stockCode: "018260", stockName: "삼성에스디에스", market: "KOSPI" },
  { stockCode: "247540", stockName: "에코프로비엠", market: "KOSDAQ" },
  { stockCode: "086520", stockName: "에코프로", market: "KOSDAQ" },
  { stockCode: "196170", stockName: "알테오젠", market: "KOSDAQ" },
  { stockCode: "403870", stockName: "HPSP", market: "KOSDAQ" },
  { stockCode: "357780", stockName: "솔브레인", market: "KOSDAQ" },
  { stockCode: "263750", stockName: "펄어비스", market: "KOSDAQ" },
  { stockCode: "293490", stockName: "카카오게임즈", market: "KOSDAQ" },
  { stockCode: "041510", stockName: "에스엠", market: "KOSDAQ" },
  { stockCode: "035900", stockName: "JYP Ent.", market: "KOSDAQ" },
  { stockCode: "145020", stockName: "휴젤", market: "KOSDAQ" },
  { stockCode: "328130", stockName: "루닛", market: "KOSDAQ" },
  { stockCode: "091990", stockName: "셀트리온헬스케어", market: "KOSDAQ" },
  { stockCode: "112040", stockName: "위메이드", market: "KOSDAQ" },
  { stockCode: "036570", stockName: "엔씨소프트", market: "KOSDAQ" },
  { stockCode: "251270", stockName: "넷마블", market: "KOSDAQ" },
  { stockCode: "068760", stockName: "셀트리온제약", market: "KOSDAQ" },
  { stockCode: "214150", stockName: "클래시스", market: "KOSDAQ" },
  { stockCode: "058470", stockName: "리노공업", market: "KOSDAQ" },
  { stockCode: "240810", stockName: "원익IPS", market: "KOSDAQ" },
  { stockCode: "039030", stockName: "이오테크닉스", market: "KOSDAQ" },
  { stockCode: "005935", stockName: "삼성전자우", market: "KOSPI" },
  { stockCode: "003670", stockName: "포스코퓨처엠", market: "KOSPI" },
  { stockCode: "010950", stockName: "S-Oil", market: "KOSPI" },
  { stockCode: "009830", stockName: "한화솔루션", market: "KOSPI" },
  { stockCode: "011170", stockName: "롯데케미칼", market: "KOSPI" },
  { stockCode: "024110", stockName: "기업은행", market: "KOSPI" },
  { stockCode: "030200", stockName: "KT", market: "KOSPI" },
  { stockCode: "051900", stockName: "LG생활건강", market: "KOSPI" },
  { stockCode: "097950", stockName: "CJ제일제당", market: "KOSPI" },
  { stockCode: "271560", stockName: "오리온", market: "KOSPI" },
  { stockCode: "139480", stockName: "이마트", market: "KOSPI" },
  { stockCode: "000810", stockName: "삼성화재", market: "KOSPI" },
  { stockCode: "010140", stockName: "삼성중공업", market: "KOSPI" },
  { stockCode: "009540", stockName: "HD한국조선해양", market: "KOSPI" },
  { stockCode: "042660", stockName: "한화오션", market: "KOSPI" },
  { stockCode: "064350", stockName: "현대로템", market: "KOSPI" },
  { stockCode: "012450", stockName: "한화에어로스페이스", market: "KOSPI" },
  { stockCode: "047810", stockName: "한국항공우주", market: "KOSPI" },
  { stockCode: "086280", stockName: "현대글로비스", market: "KOSPI" },
  { stockCode: "000720", stockName: "현대건설", market: "KOSPI" },
  { stockCode: "003490", stockName: "대한항공", market: "KOSPI" },
  { stockCode: "008770", stockName: "호텔신라", market: "KOSPI" },
  { stockCode: "011070", stockName: "LG이노텍", market: "KOSPI" },
  { stockCode: "016360", stockName: "삼성증권", market: "KOSPI" },
  { stockCode: "071050", stockName: "한국금융지주", market: "KOSPI" },
  { stockCode: "138040", stockName: "메리츠금융지주", market: "KOSPI" },
  { stockCode: "326030", stockName: "SK바이오팜", market: "KOSPI" },
  { stockCode: "000100", stockName: "유한양행", market: "KOSPI" },
  { stockCode: "128940", stockName: "한미약품", market: "KOSPI" },
  { stockCode: "022100", stockName: "포스코DX", market: "KOSDAQ" },
  { stockCode: "277810", stockName: "레인보우로보틱스", market: "KOSDAQ" },
  { stockCode: "056190", stockName: "에스에프에이", market: "KOSDAQ" },
  { stockCode: "005290", stockName: "동진쎄미켐", market: "KOSDAQ" },
  { stockCode: "084370", stockName: "유진테크", market: "KOSDAQ" },
  { stockCode: "140860", stockName: "파크시스템스", market: "KOSDAQ" },
  { stockCode: "348370", stockName: "엔켐", market: "KOSDAQ" },
  { stockCode: "141080", stockName: "리가켐바이오", market: "KOSDAQ" },
  { stockCode: "195940", stockName: "HK이노엔", market: "KOSDAQ" },
  { stockCode: "067160", stockName: "숲", market: "KOSDAQ" },
  { stockCode: "122870", stockName: "와이지엔터테인먼트", market: "KOSDAQ" },
  { stockCode: "086900", stockName: "메디톡스", market: "KOSDAQ" },
  { stockCode: "131970", stockName: "두산테스나", market: "KOSDAQ" },
  { stockCode: "192080", stockName: "더블유게임즈", market: "KOSDAQ" },
  { stockCode: "213420", stockName: "덕산네오룩스", market: "KOSDAQ" },
  { stockCode: "098460", stockName: "고영", market: "KOSDAQ" },
  { stockCode: "036930", stockName: "주성엔지니어링", market: "KOSDAQ" },
  { stockCode: "237690", stockName: "에스티팜", market: "KOSDAQ" },
  { stockCode: "145720", stockName: "덴티움", market: "KOSDAQ" },
  { stockCode: "319660", stockName: "피에스케이", market: "KOSDAQ" },
];

export function getStocksByMarket(market: Market): Stock[] {
  return KOREAN_STOCKS.filter((stock) => stock.market === market);
}

export function getYahooSymbol(stockCode: string, market: Market): string {
  const suffix = market === "KOSDAQ" || market === "KONEX" ? "KQ" : "KS";
  return `${stockCode}.${suffix}`;
}

export function findStockByCode(stockCode: string): Stock | undefined {
  return KOREAN_STOCKS.find((stock) => stock.stockCode === stockCode);
}
